# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Category.create(title:'Action')
Category.create(title:'Comedies')
Category.create(title:'SciFi')

Video.create(title: "Monk", description: "This is a test video about stars and butterflies", small_cover_url: "/tmp/monk.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 1 )
Video.create(title: "Family Guy", description: "Second video amazing", small_cover_url: "/tmp/family_guy.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id:2)
Video.create(title: "Futurama", description: "Third video amazing", small_cover_url: "/tmp/futurama.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 3)
Video.create(title: "Monk", description: "This is a test video about stars and butterflies", small_cover_url: "/tmp/monk.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 1 )
Video.create(title: "Family Guy", description: "Second video amazing", small_cover_url: "/tmp/family_guy.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id:2)
Video.create(title: "Futurama", description: "Third video amazing", small_cover_url: "/tmp/futurama.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 3)
Video.create(title: "Monk", description: "This is a test video about stars and butterflies", small_cover_url: "/tmp/monk.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 1 )
Video.create(title: "Family Guy", description: "Second video amazing", small_cover_url: "/tmp/family_guy.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id:2)
Video.create(title: "Futurama", description: "Third video amazing", small_cover_url: "/tmp/futurama.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 3)

Video.create(title: "Monk", description: "This is a test video about stars and butterflies", small_cover_url: "/tmp/monk.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 1 )
Video.create(title: "Family Guy", description: "Second video amazing", small_cover_url: "/tmp/family_guy.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id:2)
Video.create(title: "Futurama", description: "Third video amazing", small_cover_url: "/tmp/futurama.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 3)
Video.create(title: "Monk", description: "This is a test video about stars and butterflies", small_cover_url: "/tmp/monk.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 1 )
Video.create(title: "Family Guy", description: "Second video amazing", small_cover_url: "/tmp/family_guy.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id:2)
Video.create(title: "Futurama", description: "Third video amazing", small_cover_url: "/tmp/futurama.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 3)
Video.create(title: "Monk", description: "This is a test video about stars and butterflies", small_cover_url: "/tmp/monk.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 1 )
Video.create(title: "Family Guy", description: "Second video amazing", small_cover_url: "/tmp/family_guy.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id:2)
Video.create(title: "Futurama", description: "Third video amazing", small_cover_url: "/tmp/futurama.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 3)
Video.create(title: "Monk", description: "This is a test video about stars and butterflies", small_cover_url: "/tmp/monk.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 1 )
Video.create(title: "Family Guy", description: "Second video amazing", small_cover_url: "/tmp/family_guy.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id:2)
Video.create(title: "Futurama", description: "Third video amazing", small_cover_url: "/tmp/futurama.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 3)
Video.create(title: "Monk", description: "This is a test video about stars and butterflies", small_cover_url: "/tmp/monk.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 1 )
Video.create(title: "Family Guy", description: "Second video amazing", small_cover_url: "/tmp/family_guy.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id:2)
Video.create(title: "Futurama", description: "Third video amazing", small_cover_url: "/tmp/futurama.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 3)
Video.create(title: "Monk", description: "This is a test video about stars and butterflies", small_cover_url: "/tmp/monk.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 1 )
Video.create(title: "Family Guy", description: "Second video amazing", small_cover_url: "/tmp/family_guy.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id:2)
Video.create(title: "Futurama", description: "Third video amazing", small_cover_url: "/tmp/futurama.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 3)

Video.create(title: "Monk", description: "This is a test video about stars and butterflies", small_cover_url: "/tmp/monk.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 1 )
Video.create(title: "Family Guy", description: "Second video amazing", small_cover_url: "/tmp/family_guy.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id:2)
Video.create(title: "Futurama", description: "Third video amazing", small_cover_url: "/tmp/futurama.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 3)
Video.create(title: "Monk", description: "This is a test video about stars and butterflies", small_cover_url: "/tmp/monk.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 1 )
Video.create(title: "Family Guy", description: "Second video amazing", small_cover_url: "/tmp/family_guy.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id:2)
Video.create(title: "Futurama", description: "Third video amazing", small_cover_url: "/tmp/futurama.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 3)
Video.create(title: "Monk", description: "This is a test video about stars and butterflies", small_cover_url: "/tmp/monk.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 1 )
Video.create(title: "Family Guy", description: "Second video amazing", small_cover_url: "/tmp/family_guy.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id:2)
Video.create(title: "Futurama", description: "Third video amazing", small_cover_url: "/tmp/futurama.jpg", large_cover_url:"/tmp/monk_large.jpg", category_id: 3)